exports.MemStore = require('./src/mem-store')
exports.config = require('./src/config')
exports.connectPeers = require('./src/connect-peers')
exports.getIpfsPeerId = require('./src/get-ipfs-peer-id')
exports.startIpfs = require('./src/start-ipfs')
exports.stopIpfs = require('./src/stop-ipfs')
exports.testAPIs = require('./src/test-apis.js')
exports.waitForPeers = require('./src/wait-for-peers')
